services:

  mhrv:
    image: ghcr.io/therealaleph/mhrv-tunnel-node:latest
    container_name: mhrv
    restart: unless-stopped
    environment:
      TUNNEL_AUTH_KEY: ${TUNNEL_AUTH_KEY}
    expose:
      - "8080"
    networks:
      - web

networks:
  web:
    external: true
