services:

  masterdns:
    image: ghcr.io/masterking32/masterdnsvpn:latest
    container_name: masterdns
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./data:/data
    ports:
      - "53:53/tcp"
      - "53:53/udp"
